// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@silence.local"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/speak": {
            "post": {
                "description": "Accepts audio in multipart/form-data format and returns transcribed text using the configured transcription provider. Supports both PCM and WAV formats.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audio"
                ],
                "summary": "Transcribe audio",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (PCM or WAV format, max 32MB)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Audio format: 'pcm_s16le_16' or 'wav'. Defaults to 'pcm_s16le_16' for lower latency. Use pcm_s16le_16 for 16-bit PCM at 16kHz, mono, little-endian.",
                        "name": "file_format",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ISO-639-1 or ISO-639-3 language code. Use 'auto' or omit for auto-detection. Examples: 'en', 'es', 'fr'",
                        "name": "language_code",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transcription successful",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid format, empty audio, etc.)",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid audio format"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1629840000
                }
            }
        },
        "handlers.SuccessResponse": {
            "type": "object",
            "properties": {
                "audio_length": {
                    "type": "integer",
                    "example": 15
                },
                "language_code": {
                    "type": "string",
                    "example": "en"
                },
                "text": {
                    "type": "string",
                    "example": "Hello world, this is a transcription"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1629840000
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Silence API",
	Description:      "AI-powered audio transcription service with ElevenLabs integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
